version: '3.7'

services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - alectrion-user-network
      - alectrion-network

  user_api:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - alectrion-user-network
      - alectrion-network
    ports:
      - 4001:4001
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; yarn & yarn prisma migrate dev init && yarn dev"
    depends_on:
      - db

networks:
  alectrion-user-network:
  alectrion-network:
    external: true
