version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - alectrion-user-network
      - alectrion-network

  user_api:
    container_name: user_api
    image: user_api
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - '4001:4001'
    command: bash -c "yarn && yarn migration:generate && yarn migration:run && yarn dev"
    networks:
      - alectrion-user-network
      - alectrion-network

networks:
  alectrion-user-network:
  alectrion-network:
    external: true
